### ISSUE TITLE
Updating Pypi

### ISSUE THREAD

**Issue by Arduous** [tkuebler/pyping#1]
Hello,

I installed pyping 0.0.5 from Pypi, ported it to Python 3.5 and retabbed it. Willing to submit a patch, I only then found out that the original repository is no longer available, and that you already did the work -_- . Do you think it is possible to push a, let's say, 0.0.6 to Pypi?

Cheers.

**Comment by tkuebler** [comment]
Hey Samuel.

Coming from other languages I find the python module repository to be infuriatingly obtuse and poorly designed.  (perl, ruby, java, etc are all much better )    It sucks because of course I really like python as a language.

I opened a case with the absentee admins requesting access to the pyping module, but have heard nothing in over a year… 

Feel free to submit yours as pyping 0.0.6, or if you want me to do it I could push what I have I suppose - I’m just pulling my updated module from GitHub for now and continuing to attempt to get control of the pyping module.

Do you have your code in GitHub? 

Only the humble improve.

**Comment by tkuebler** [comment]
Here's the support request..

https://sourceforge.net/p/pypi/support-requests/743/

**Comment by Arduous** [comment]
Hello,

I am with you regarding Pypi. Given that my modifications are diverging from yours on a few added or removed spaces this and there, I do not want to push my modifications to Github. In my mind it would just add more noise.

In the while, I came across some https://github.com/samuel/python-ping (not related to me at all). This repo seems dormant, but 2 forks ( https://github.com/l4m3rx/python-ping and https://github.com/certator/pyping) seem pretty active and up to date. Do you know them?

My plan is to try to understand how Pipy is managed, and if possible get the ownership of pyping transferred.

Cheers

**Comment by tkuebler** [comment]
time passed

**Comment by Arduous** [comment]
Obviously. I guess this needs predated my move to Home Assistant. Have a good one.
